COMMENT =		a Python library to sanitize/validate paths

MODPY_EGG_VERSION =	3.2.0
DISTNAME =		pathvalidate-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}
CATEGORIES =		devel
HOMEPAGE =		https://github.com/thombashi/pathvalidate

# MIT
PERMIT_PACKAGE =	Yes

FLAVORS =		python3
FLAVOR =		python3

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

NO_TEST =		Yes

.include <bsd.port.mk>
