COMMENT =		QPACK compression library for use with HTTP/3

DIST_TUPLE +=		github litespeedtech ls-qpack v2.5.4 .

SHARED_LIBS =		ls-qpack	1.0 # 2.5.4

CATEGORIES =		archivers devel www

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		devel/cmake

CONFIGURE_ARGS =	-DBUILD_SHARED_LIBS=ON

.include <bsd.port.mk>
